name: MD5-Secret Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Build
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "rf.wangchn@foxmail.com"
          git config --global user.name "ruofei"
          npm i
          npm run build

      - name: Deploy 2 Github Pages (repo - md5-secret)
        run: |
          cp ./build ~ -rfv
          cd ~/build
          git config --global init.defaultBranch docs
          git init
          git add .
          git commit 'initialize'
          git remote add origin git@github.com:smpower/md5-secret.git
          git push --set-upstream origin docs
